### ISSUE TITLE
About auto-upgrade docker image by connecting repo to docker-hub

### ISSUE THREAD

**Issue by fanvinga** [fialakarel/docker-winbox#5]
I recently noticed that the images on the docker hub don't seem to be automatically updated with the merge of the pull request I initiated.The version of winbox inside the image is still 3.28.

**Comment by fialakarel** [comment]
@fanvinga The problem is that the free plan of Docker Hub discontinued this option. IMHO the only solution is to use GitHub actions to build it a push it to Docker Hub. I don't want to pay 5$ per month just for this simple thing and running it locally and pushing it manually is not transparent enough.

**Comment by fanvinga** [comment]
> IMHO the only solution is to use GitHub actions to build it a push it to Docker Hub.

That would be great!

**Comment by fialakarel** [comment]
It's done. New versions will be built and pushed automatically.
